### ISSUE TITLE
No zipcode validation on the change address page

### ISSUE THREAD

**Issue by karelvh** [hlohaus/SheRegistrationExtension#1]
## Actual behaviour

    The plugin works and validates zipcodes on the registration page during checkout,

but does not work on the "change address" page in the profile section.
![change address does not work](https://user-images.githubusercontent.com/9048726/62836284-eae16380-bc61-11e9-9794-26c7c0c36271.jpg)

## Expected behaviour

    Zipcode validation should happen on all page where a zipcode is asked.

## Environment

PHP7, Apache, Shopware 5.5.10

## Steps to reproduce

1. Go to the profile page of a Shopware webshop.
2. Click "change address"
3. Zip code validation does not work on this page

## Checklist

- [x] I have checked [all issues](https://github.com/hlohaus/SheRegistrationExtension/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x] I am using the latest stable version of this plugin.

**Comment by hlohaus** [comment]
I can not adjust the problem. For me it works at this point too.

https://i.imgur.com/4BtD6jc.png
